#!/usr/bin/env python
#
# Based on
# http://www.secdev.org/projects/scapy/doc/usage.html

from scapy.all import *
import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('host', metavar='host', nargs='+',
                        help='the target host for the trace')
    parser.add_argument('--output', # type=argparse.FileType('w'),
                        dest='output', default='graph.svg',
                        help='where to write the SVG graph')

    args = parser.parse_args()
    print args.host
    print args.output
    
    res,unans = traceroute(args.host,dport=[80,443],maxttl=20,retry=-2)
    res.graph(target="> %s" % args.output)

if __name__ == '__main__':
    main()
